require: rubocop-rails

Rails:
  Enabled: true
AllCops:
  NewCops: enable
  Exclude:
    - 'config/puma.rb'
    - 'bin/*'
    - 'vendor/*/'
  SuggestExtensions: false
Lint/MissingSuper:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/*/'
    - 'config/environments/*'
Metrics/ClassLength:
  Max: 150
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false